# Generated by Django 5.1.3 on 2024-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_dailyreport'),
        ('members', '0002_alter_member_start_date_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='payments',
            field=models.ManyToManyField(to='members.payment'),
        ),
    ]
