# Generated by Django 5.1.3 on 2024-12-06 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.localdate)),
                ('scheduled_date', models.DateField()),
                ('is_sent', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_messages', to='members.member')),
            ],
        ),
    ]
