# Generated by Django 5.1.3 on 2024-12-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_billingmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmessage',
            name='scheduled_date',
        ),
    ]
