# Generated by Django 5.1.3 on 2024-12-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_billingmessage_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='billingmessage',
            index=models.Index(fields=['is_sent'], name='members_bil_is_sent_fa3b85_idx'),
        ),
        migrations.AddIndex(
            model_name='billingmessage',
            index=models.Index(fields=['sent_at'], name='members_bil_sent_at_7745be_idx'),
        ),
    ]
