# Generated by Django 5.1.3 on 2024-12-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_billingmessage_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmessage',
            name='sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
